### PR TITLE
Added enforcement of protocol handling for out-of-order headers

### PR DESCRIPTION
**Pull request by byronformwalt**
- Implemented validation (order and casing) of received headers. Failure must trigger a stream error (PROTOCOL_ERROR)
- Header compressor now emits pseudo-headers ahead of the rest (by partitioning supplied list)

### CODE REVIEW

**Comment by byronformwalt** [comment]
This PR is intended to fulfill closed PR #132.

File: lib/http/2/compressor.rb [hunk 1]
```diff
@@ -443,9 +443,11 @@ def header(h, buffer = Buffer.new)
       #
       # @param headers [Array] +[[name, value], ...]+
       # @return [Buffer]
-      def encode(headers)
+      def encode(headers, ensure_proper_ordering: true)
         buffer = Buffer.new
-
+        if ensure_proper_ordering
+          headers = headers.partition { |f, _| f.start_with? ':' }.inject([]) { |a, e| a + e }
```
[the remark this answers is not in the document]
Comment (HoneyryderChuck) [reply lib/http/2/compressor.rb]:
```ruby
irb(main):007:0> [[[":a", 1], [":b", 2]], [["c", 3], ["d", 4]] ].flatten
=> [":a", 1, ":b", 2, "c", 3, "d", 4]
```

are we sure we want this representation, and not an "array of pairs"?

I suggest this:

```ruby
h1, h2 = headers.partition { |f, _| f.start_with? ':' }
headers = [*h1, *h2]

File: lib/http/2/compressor.rb [hunk 2]
```diff
@@ -549,7 +551,16 @@ def header(buf)
       # @return [Array] +[[name, value], ...]+
       def decode(buf)
         list = []
-        list << @cc.process(header(buf)) until buf.empty?
+        decoded_first_regular_header = false
```
Comment (HoneyryderChuck) [inline lib/http/2/compressor.rb]: consider changing this to:

```ruby
decoding_pseudo_headers = true
```

and switching your logic regarding this variable, it'll make it easier to read it and you can just do the assignment without the `||=`.

File: lib/http/2/compressor.rb [hunk 3]
```diff
@@ -549,7 +551,16 @@ def header(buf)
...
+        until buf.empty?
+          next_header = @cc.process(header(buf))
+          is_pseudo_header = next_header.first.start_with? ':'
+          if decoded_first_regular_header && is_pseudo_header
+            fail CompressionError, 'one or more pseudo headers encountered after regular headers'
```
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: CompressionError is a subclass of ProtocolError, and therefore I raising such an error does adhere to the spec... am I interpret.  Since the error is being raised from compressor.rb, I thought you would have preferred the subclass, CompressionError.  Please, confirm you really want ProtocolError to be raised.

File: lib/http/2/compressor.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: @HoneyryderChuck Yes, that would be much cleaner.

File: lib/http/2/compressor.rb [hunk 4]
```diff
@@ -549,7 +551,16 @@ def header(buf)
...
+          end
+          decoded_first_regular_header ||= !is_pseudo_header
+          list << next_header
+        end
```
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: @igrigorik Can you please explain what you don't like about the solution so I can address the problem? (e.g. readability, efficiency, etc.)

File: lib/http/2/compressor.rb [hunk 5]
```diff
@@ -443,9 +443,11 @@ def header(h, buffer = Buffer.new)
       #
       # @param headers [Array] +[[name, value], ...]+
       # @return [Buffer]
-      def encode(headers)
+      def encode(headers, ensure_proper_ordering: true)
```
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: @igrigorik I'm missing something else here.  I do not understand why the flag solution does not scale.  Can you please explain why?

File: lib/http/2/compressor.rb (hunk 2 above)
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: @HoneyryderChuck Sounds good.

**Comment by byronformwalt** [comment]
Once I get responses back from @igrigorik, I should be able to update the PR to reflect everyone's feedback, unless there are dissenting opinions.

**Comment by byronformwalt** [comment]
... but I would also really appreciate some feedback on the changes I made to the Rspec testing logic.  I think we can do better than what I proposed.

File: lib/http/2/compressor.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: Thanks for clarifying what you meant by scalability.  I will setup the bytes on wire, bypassing the client for this test case, as you proposed.

File: lib/http/2/compressor.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: Thanks for confirming.

File: lib/http/2/compressor.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: Will do.

**Comment by byronformwalt** [comment]
Ok.  I have everything I need.  I'll update the PR today.

File: lib/http/2/compressor.rb [hunk 6]
```diff
@@ -549,7 +550,16 @@ def header(buf)
       # @return [Array] +[[name, value], ...]+
       def decode(buf)
         list = []
-        list << @cc.process(header(buf)) until buf.empty?
+        decoding_pseudo_headers = true
```
Comment (igrigorik) [inline lib/http/2/compressor.rb]: As a brief but related aside...

> Pseudo-header fields MUST NOT appear in trailers. Endpoints MUST treat a request or response that contains undefined or invalid pseudo-header fields as malformed (Section 8.1.2.6).

Proposed update does not break trailer support, but we're also not enforcing the above variant. At a minimum, perhaps worth flagging as a TODO. That said, this also probably does not belong in Compressor, but should be handled in the stream, as that's the right place to track state for initial set of headers vs trailers.

File: lib/http/2/compressor.rb [hunk 7]
```diff
@@ -549,7 +550,16 @@ def header(buf)
...
+        until buf.empty?
+          next_header = @cc.process(header(buf))
+          is_pseudo_header = next_header.first.start_with? ':'
+          if !decoding_pseudo_headers && is_pseudo_header
+            fail ProtocolError, 'one or more pseudo headers encountered after regular headers'
```
Comment (igrigorik) [inline lib/http/2/compressor.rb]: Hmm, one gotcha here..

https://github.com/igrigorik/http-2/blob/master/lib/http/2/connection.rb#L609-L611

^ we'll end up raising compression error regardless. I think we need to update that logic as well.

File: lib/http/2/compressor.rb (hunk 6 above)
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: You're right.  I think it needs to be opened as a separate issue, though.  There may be several other similar MUST requirements that are not being enforced.  For example, in Section 8.1.1, it says: 

> Pseudo-header fields are only valid in the context in which they are defined. Pseudo-header fields defined for requests MUST NOT appear in responses; pseudo-header fields defined for responses MUST NOT appear in requests. Pseudo-header fields MUST NOT appear in trailers. Endpoints MUST treat a request or response that contains undefined or invalid pseudo-header fields as malformed (Section 8.1.2.6).

For example, you cannot include a `:status` pseudo header in a request nor a `:method` pseudo header in a response.  As far as I can tell, the gem does not enforce this requirement either.  My recommendation is that we create an overarching issue that allows other interested contributors to comment on header validation so that we can gather input from the community and prioritize how we proceed/divide up the work.  What do you think?

File: lib/http/2/compressor.rb (hunk 7 above)
Comment (byronformwalt) [reply lib/http/2/compressor.rb]: I have updated the logic in `connection.rb`.  Pushing momentarily.

**Comment by byronformwalt** [comment]
Two other ideas came to me last night.  For the scope of this PR, we modified the compression spec tests.  However, after looking more deeply at the HTTP/2 spec, it seems appropriate that we would want to write additional client and server specs that are written against each documented requirement for header requests/responses.  A new branch could be created on the official repo with all of these tests committed, with many of them failing.  Contributors could then create PRs on this development branch, with each PR addressing one or more failing tests, as appropriate.  Once all new tests are passing in the branch, it can be merged back into the main branch.  What do you think about applying this workflow as an efficient means of dividing the labor among contributors and collaborators while keeping changes merged into the main branch pristine in the context of passing all tests?

**Comment by byronformwalt** [comment]
I just noticed that Open Issue #72 looks like it was intended to follow a similar approach, but has no dedicated branch, PRs, or recent activity.  Am I right?  Do you want to continue the conversation on that issue thread or should we create a separate issue?

**Comment by ioquatix** [comment]
@igrigorik I'm not sure what I can add here. I see both sides of the coin. I'm happy for you to take the library in whatever direction you feel is appropriate, and it does make sense to support the RFC by default. But I also believe it shouldn't impact performance and I believe it should be optional for people who want to use this library in different ways, e.g. pen testing, crafting bad requests, testing, etc. This PR adds a specific flag to `#headers` where as my proposal was to add a general `strict` flag which I think fits better with all the changes required to correctly honour the requirements of the relevant RFCs as is now being discussed but that I anticipated in the previous discussion. My preference is for the low level interfaces to simply document the requirements of the arguments in order to be compliant, rather than forcefully adjust things internally at the expense of performance. I think that it's the concern of higher level libraries to be compliant or not, but I see the value in catching as many issues as possible. The way I did this in `async` was by explicitly adding a debugging layer which is only present when running tests/specs. I think this way, you catch compliance issues during testing, but you avoid overhead in production.

**Comment by ioquatix** [comment]
Just to clarify, personally, I prefer the wrapper approach over flags like `strict` or `ensure_proper_ordering`. Because I don't think they should be part of the public interface. To me, I look at `ensure_proper_ordering` introduces complexity on a per-stream basis that the user should not need to be aware of, and as we've seen, it's not just a matter of ordering, but header key case, and that some pseudo-headers are not valid in various contexts. So, are you going to add more flags? `ensure_valid_keys` and `ensure_lowercase_keys`, etc. I don't feel like it's a great approach, personally.

**Comment by ioquatix** [comment]
After reviewing this issue and others, I also think that most of these should be hard errors (i.e. when some kind of strict mode is on, it should raise an exception, and strict mode should be the default). I don't think we should be transparently accepting non-compliant data either from the network, or from higher level code. Some examples would include things like:

- Are header keys lower case?
- Are header keys limited to 7-bit ASCII?
- Has the user specified invalid headers (e.g. `Transfer-Encoding`, `Expect`)?
- Do request and responses have the correct pseudo-headers and no invalid headers?
- Do pseudo headers have correctly formatted values (as defined by the RFC)?
- If the content-length header present does it match up with the amount of data sent?
- Don't allow headers to be sent in incorrect states (i.e. calling `#headers` twice at the start of a stream).

I'm sure there are others, but in my mind, if you really want to force correct usage of the protocol, this is at least some minimum. There are probably heaps more.

**Comment by byronformwalt** [comment]
@ioquatix I like the approach where users have the option to disable strict conformance testing.  I see the value in that for applications where one of the two conditions applies:

1. You have already ensured that the caller is in conformance with the spec, thereby obviating the need to do conformance testing at the expense of efficiency.
2. You would like to test an application (perhaps a server or client written in a different language) and would like to use this gem to perform the role of a bad actor, giving you low-level control over its behavior.

If conformance checking were abstracted into a one or more dedicated methods, it would be straightforward to disable them.  Furthermore, keyword arguments could be used to allow the user to specify in a hash which types of conformance checking should be disabled.  While I'm not interested pushing development in this direction, I can clearly see how it would be valuable to you.

**Comment by ioquatix** [comment]
I don't have particular use cases that require either strict or non-strict functionality. I ran into issues using this gem because it was non-conformance and didn't issue any warnings/errors. So, I've had some frustrating experiences w.r.t. the behaviours being discussed. As have others. But, I fixed them, tested, and moved on. It was really just poor visibility of the issues that caused the conformance issues/failures. A lack of documentation relating to conforming behaviour is one aspect of the problem and possibly one of the main ones to take initially. I would suggest that the documentation specifically links to the relevant RFCs.

W.r.t. the strict flag: I only try to anticipate my future use cases, and what people are capable of dealing with. As has been already said, we don't want to make this too complicated for end users. I wish there was a strict flag which was on by default. It would have saved me a lot of time when I started using this code.

I also respect the need for this gem to be conforming by default, but I have trouble accepting the performance cost. However, strict by default seems logical. I imagine someone would implement their code with strict by default. Once their usage is conforming, they can turn of strict at their won peril to remove checks which have necessary performance implications. In my mind, there isn't really a use case for switching off conformance on a function by function basis. In my mind, one tests/develops with strict mode ON, and then turns it OFF in production. Conformance issues within a strict mode should be an exceptional case and cause your code to fail hard. The correct solution is to actually fix your code to be conformant. Some of these issues are beyond the scope of this gem being able to fix (but at least could be reported/issue a warning).

There are some additional concerns w.r.t. network input. We don't control network input so a server might always run with strict mode on. Ideally we always validate network input, since that's going to be the most likely avenue for an attack based on non-conformance (e.g. similar to how HTTP1 proxies sometimes failed to process multiple content-length headers correctly, or having both content-length and chunked transfer-encoding, both attacks which have the potential to leak side channel data/requests).

**Comment by igrigorik** [comment]
> after looking more deeply at the HTTP/2 spec, it seems appropriate that we would want to write additional client and server specs that are written against each documented requirement for header requests/responses. A new development branch could be created on the official repo with all of these tests committed, with many of them failing. Contributors could then create PRs on that new development branch, with each PR addressing one or more failing tests, as appropriate. Once all new tests are passing in the branch, it can be merged back into the main branch.

I like the idea. FWIW, we can also mark tests as pending and develop on master.

> I just noticed that Open Issue #72 looks like it was intended to follow a similar approach, but has no dedicated branch, PRs, or recent activity. Am I right? Do you want to continue the conversation on that issue thread or should we create a separate issue?

In theory we could continue there, but if you want to start a more scoped discussion (e.g. focused on header processing), that's works too.

> @ioquatix I also respect the need for this gem to be conforming by default, but I have trouble accepting the performance cost. 

I'm not disputing there is overhead, but I'm not convinced and would like to see some real-world data that this significant enough to carve different code paths for. If it's an issue, we can investigate how to make it more performant, before we toggle it off. That aside, strong +1 for addressing all of the points you raised in https://github.com/igrigorik/http-2/pull/136#issuecomment-406766592.

---

To close this off, I think we're all on the same page wrt to landing the current patch. I'll merge and resolve this, and let's start a new thread to followthrough on all the other bits being discussed here.

p.s. @byronformwalt kudos and thank you for the patience and perseverance with this work! :-)

**Comment by igrigorik** [comment]
Thanks all. 

With this updated landed, do you want to see a new point release of the gem, or is there other work we want to tackle first?

**Comment by byronformwalt** [comment]
Reopening so this can be merged.  (I thought a closed PR could be merged.)

**Comment by igrigorik** [comment]
👍

**Comment by byronformwalt** [comment]
@igrigorik Did you plan on hitting the merge button, or did you want me to?  My vote would be to make this a release point.

**Comment by igrigorik** [comment]
Merged. I'm happy to push a 0.9.2 — any objections?

**Comment by igrigorik** [comment]
@ioquatix new API? How so? This seems like an under the hood change that nobody should notice. 

To be clear, I'm not against 0.10, but want to understand your reasoning.

**Comment by ioquatix** [comment]
The headers method has new arguments

**Comment by ioquatix** [comment]
Also new #closed? Methods

**Comment by ioquatix** [comment]
> Err, which method / new arguments? Here's the full diff: c3e5733...1cb2518

Okay, there have been so many PRs, I didn't realise it was no longer optional.

**Comment by igrigorik** [comment]
No worries, just wanted to make sure I didn't miss anything on this end. 

0.10.0 should be up on rubygems now. Thanks everyone, once again.. :-)

**Comment by kenichi** [comment]
just a quick note to say all my tests are passing with no changes for header order:

https://github.com/kenichi/h2/commit/0b9820815c7c9841eff578ccc5501099831e843b#diff-abea678ba5dc6bfeaaecf8b9f735d1deR20
https://travis-ci.org/kenichi/h2/builds/408256122

**Comment by kenichi** [comment]
i'm not sure if this is a bug in my nginx http2 module but it seems that the decompressor may return `nil` headers during decode, and so with these changes, i'm getting this error on 91b8972:

```
http-2 $ bundle exec ruby example/client.rb https://nakamura.io/ip
Sending HTTP 2.0 request
Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
Sent frame: {:type=>:headers, :flags=>[:end_headers, :end_stream], :payload=>{":scheme"=>"https", ":method"=>"GET", ":authority"=>"nakamura.io:443", ":path"=>"/ip", "accept"=>"*/*"}, :stream=>1}
[Stream 1]: closing client-end of the stream
Received frame: {:length=>18, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 128], [:settings_initial_window_size, 65536], [:settings_max_frame_size, 16777215]]}
Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
Received frame: {:length=>4, :type=>:window_update, :flags=>[], :stream=>0, :increment=>2147418112}
Received frame: {:length=>0, :type=>:settings, :flags=>[:ack], :stream=>0, :payload=>[]}
Received frame: {:length=>54, :type=>:headers, :flags=>[:end_headers], :stream=>1, :payload=>" \x88v\x89\xAAcU\xE5\x80\xAE\x16\xD7\x17a\x96\xC3a\xBE\x94\x13\xAAe\xB6\x85\x04\x00\xBC\xA0\x85p-\xDCe\xD51h\xDF_\x8B\x1Du\xD0b\r&=LtA\xEA\\\x0230"}
Sent frame: {:type=>:goaway, :last_stream=>1, :error=>:internal_error, :payload=>nil}
HTTP2::Error::InternalError exception: undefined method `first' for nil:NilClass - closing socket.
        /Users/kenichi/src/ruby/http-2/lib/http/2/compressor.rb:556:in `decode'
        /Users/kenichi/src/ruby/http-2/lib/http/2/connection.rb:606:in `decode_headers'
        /Users/kenichi/src/ruby/http-2/lib/http/2/connection.rb:250:in `receive'
        example/client.rb:116:in `<main>'
```

this works with 0.9.1, nghttp, curl --http2-prior-knowledge, and chrome. if you edit either 0.9.1 or 0.10.0 decode to "puts next_header" (you'll have to split the line up a bit on 0.9.1), you can see that this payload is causing it (`@cc.process(header(buf))`) to return a nil, which looks like it might be expected since we see `list.compact` on the next line.

a cursory fix might be just to wrap that new order-checking block in an if:

```diff
diff --git a/lib/http/2/compressor.rb b/lib/http/2/compressor.rb
index 9569e81..cedbd39 100644
--- a/lib/http/2/compressor.rb
+++ b/lib/http/2/compressor.rb
@@ -552,15 +552,15 @@ module HTTP2
         list = []
         decoding_pseudo_headers = true
         until buf.empty?
-          next_header = @cc.process(header(buf))
-          is_pseudo_header = next_header.first.start_with? ':'
-          if !decoding_pseudo_headers && is_pseudo_header
-            fail ProtocolError, 'one or more pseudo headers encountered after regular headers'
+          if next_header = @cc.process(header(buf))
+            is_pseudo_header = next_header.first.start_with? ':'
+            if !decoding_pseudo_headers && is_pseudo_header
+              fail ProtocolError, 'one or more pseudo headers encountered after regular headers'
+            end
+            decoding_pseudo_headers = is_pseudo_header
+            list << next_header
           end
-          decoding_pseudo_headers = is_pseudo_header
-          list << next_header
         end
-        list.compact
       end
     end
   end
```

which may also let us remove that `list.compact` at the end. thoughts?
